// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: nlp/dialog/segment.proto

package nlp

import (
	_ "github.com/ClarabridgeInc/ingestion-callback/internal/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Segment types.
type SegmentTypeEnum int32

const (
	SegmentTypeEnum_SEGMENT_TYPE_UNKNOWN  SegmentTypeEnum = 0
	SegmentTypeEnum_SEGMENT_TYPE_SENTENCE SegmentTypeEnum = 1
	SegmentTypeEnum_SEGMENT_TYPE_TURN     SegmentTypeEnum = 2
	SegmentTypeEnum_SEGMENT_TYPE_TOKEN    SegmentTypeEnum = 3
)

// Enum value maps for SegmentTypeEnum.
var (
	SegmentTypeEnum_name = map[int32]string{
		0: "SEGMENT_TYPE_UNKNOWN",
		1: "SEGMENT_TYPE_SENTENCE",
		2: "SEGMENT_TYPE_TURN",
		3: "SEGMENT_TYPE_TOKEN",
	}
	SegmentTypeEnum_value = map[string]int32{
		"SEGMENT_TYPE_UNKNOWN":  0,
		"SEGMENT_TYPE_SENTENCE": 1,
		"SEGMENT_TYPE_TURN":     2,
		"SEGMENT_TYPE_TOKEN":    3,
	}
)

func (x SegmentTypeEnum) Enum() *SegmentTypeEnum {
	p := new(SegmentTypeEnum)
	*p = x
	return p
}

func (x SegmentTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_nlp_dialog_segment_proto_enumTypes[0].Descriptor()
}

func (SegmentTypeEnum) Type() protoreflect.EnumType {
	return &file_nlp_dialog_segment_proto_enumTypes[0]
}

func (x SegmentTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentTypeEnum.Descriptor instead.
func (SegmentTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_nlp_dialog_segment_proto_rawDescGZIP(), []int{0}
}

//*
// Segment
//
// version              Message version.
// participant_id       The id number corresponding to the the Participant.
// text                 The actual text segment.
// start                The start time of the segment in milliseconds.
// end                  The end time of the segment in milliseconds.
type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ParticipantId int32  `protobuf:"varint,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Start         int64  `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	End           int64  `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nlp_dialog_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_dialog_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_nlp_dialog_segment_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Segment) GetParticipantId() int32 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

func (x *Segment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Segment) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_nlp_dialog_segment_proto protoreflect.FileDescriptor

var file_nlp_dialog_segment_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x6c, 0x70, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x6c, 0x70, 0x2e,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x3a, 0x03,
	0xc0, 0x3e, 0x02, 0x2a, 0x75, 0x0a, 0x0f, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x19, 0x0a, 0x15, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x53, 0x45, 0x4e, 0x54, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x53,
	0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x55, 0x52, 0x4e,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x47, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x03, 0x42, 0x2c, 0x0a, 0x20, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x50, 0x01,
	0x5a, 0x06, 0x70, 0x62, 0x2f, 0x6e, 0x6c, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nlp_dialog_segment_proto_rawDescOnce sync.Once
	file_nlp_dialog_segment_proto_rawDescData = file_nlp_dialog_segment_proto_rawDesc
)

func file_nlp_dialog_segment_proto_rawDescGZIP() []byte {
	file_nlp_dialog_segment_proto_rawDescOnce.Do(func() {
		file_nlp_dialog_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_nlp_dialog_segment_proto_rawDescData)
	})
	return file_nlp_dialog_segment_proto_rawDescData
}

var file_nlp_dialog_segment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nlp_dialog_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nlp_dialog_segment_proto_goTypes = []interface{}{
	(SegmentTypeEnum)(0), // 0: nlp.dialog.SegmentTypeEnum
	(*Segment)(nil),      // 1: nlp.dialog.Segment
}
var file_nlp_dialog_segment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nlp_dialog_segment_proto_init() }
func file_nlp_dialog_segment_proto_init() {
	if File_nlp_dialog_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nlp_dialog_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nlp_dialog_segment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nlp_dialog_segment_proto_goTypes,
		DependencyIndexes: file_nlp_dialog_segment_proto_depIdxs,
		EnumInfos:         file_nlp_dialog_segment_proto_enumTypes,
		MessageInfos:      file_nlp_dialog_segment_proto_msgTypes,
	}.Build()
	File_nlp_dialog_segment_proto = out.File
	file_nlp_dialog_segment_proto_rawDesc = nil
	file_nlp_dialog_segment_proto_goTypes = nil
	file_nlp_dialog_segment_proto_depIdxs = nil
}
