// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: nlp/dialog/special-event.proto

package nlp

import (
	_ "github.com/ClarabridgeInc/ingestion-callback/internal/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Special events.
type SpecialEventEnum int32

const (
	SpecialEventEnum_SPECIAL_EVENT_NONE     SpecialEventEnum = 0
	SpecialEventEnum_SPECIAL_EVENT_HOLD     SpecialEventEnum = 1
	SpecialEventEnum_SPECIAL_EVENT_TRANSFER SpecialEventEnum = 2
	SpecialEventEnum_SPECIAL_EVENT_SILENCE  SpecialEventEnum = 3
)

// Enum value maps for SpecialEventEnum.
var (
	SpecialEventEnum_name = map[int32]string{
		0: "SPECIAL_EVENT_NONE",
		1: "SPECIAL_EVENT_HOLD",
		2: "SPECIAL_EVENT_TRANSFER",
		3: "SPECIAL_EVENT_SILENCE",
	}
	SpecialEventEnum_value = map[string]int32{
		"SPECIAL_EVENT_NONE":     0,
		"SPECIAL_EVENT_HOLD":     1,
		"SPECIAL_EVENT_TRANSFER": 2,
		"SPECIAL_EVENT_SILENCE":  3,
	}
)

func (x SpecialEventEnum) Enum() *SpecialEventEnum {
	p := new(SpecialEventEnum)
	*p = x
	return p
}

func (x SpecialEventEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpecialEventEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_nlp_dialog_special_event_proto_enumTypes[0].Descriptor()
}

func (SpecialEventEnum) Type() protoreflect.EnumType {
	return &file_nlp_dialog_special_event_proto_enumTypes[0]
}

func (x SpecialEventEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpecialEventEnum.Descriptor instead.
func (SpecialEventEnum) EnumDescriptor() ([]byte, []int) {
	return file_nlp_dialog_special_event_proto_rawDescGZIP(), []int{0}
}

//*
// SpecialEvent
//
// version        Message version.
// type           The type of special event.
// start          The start time of the segment in milliseconds.
// end            The end time of the segment in milliseconds.
type SpecialEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    SpecialEventEnum `protobuf:"varint,2,opt,name=type,proto3,enum=nlp.dialog.SpecialEventEnum" json:"type,omitempty"`
	Start   int64            `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End     int64            `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *SpecialEvent) Reset() {
	*x = SpecialEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nlp_dialog_special_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecialEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialEvent) ProtoMessage() {}

func (x *SpecialEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_dialog_special_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialEvent.ProtoReflect.Descriptor instead.
func (*SpecialEvent) Descriptor() ([]byte, []int) {
	return file_nlp_dialog_special_event_proto_rawDescGZIP(), []int{0}
}

func (x *SpecialEvent) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SpecialEvent) GetType() SpecialEventEnum {
	if x != nil {
		return x.Type
	}
	return SpecialEventEnum_SPECIAL_EVENT_NONE
}

func (x *SpecialEvent) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SpecialEvent) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_nlp_dialog_special_event_proto protoreflect.FileDescriptor

var file_nlp_dialog_special_event_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x6c, 0x70, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x6e, 0x6c, 0x70, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x1a, 0x0d, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x0c,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x3a, 0x03, 0xc0, 0x3e, 0x02, 0x2a, 0x79, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x41, 0x4c, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x50, 0x45, 0x43, 0x49, 0x41, 0x4c, 0x5f, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x5f, 0x48, 0x4f, 0x4c, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x41, 0x4c, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53,
	0x46, 0x45, 0x52, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x50, 0x45, 0x43, 0x49, 0x41, 0x4c,
	0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x49, 0x4c, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x03,
	0x42, 0x2c, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x64, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x50, 0x01, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x6e, 0x6c, 0x70, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nlp_dialog_special_event_proto_rawDescOnce sync.Once
	file_nlp_dialog_special_event_proto_rawDescData = file_nlp_dialog_special_event_proto_rawDesc
)

func file_nlp_dialog_special_event_proto_rawDescGZIP() []byte {
	file_nlp_dialog_special_event_proto_rawDescOnce.Do(func() {
		file_nlp_dialog_special_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_nlp_dialog_special_event_proto_rawDescData)
	})
	return file_nlp_dialog_special_event_proto_rawDescData
}

var file_nlp_dialog_special_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nlp_dialog_special_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nlp_dialog_special_event_proto_goTypes = []interface{}{
	(SpecialEventEnum)(0), // 0: nlp.dialog.SpecialEventEnum
	(*SpecialEvent)(nil),  // 1: nlp.dialog.SpecialEvent
}
var file_nlp_dialog_special_event_proto_depIdxs = []int32{
	0, // 0: nlp.dialog.SpecialEvent.type:type_name -> nlp.dialog.SpecialEventEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nlp_dialog_special_event_proto_init() }
func file_nlp_dialog_special_event_proto_init() {
	if File_nlp_dialog_special_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nlp_dialog_special_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecialEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nlp_dialog_special_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nlp_dialog_special_event_proto_goTypes,
		DependencyIndexes: file_nlp_dialog_special_event_proto_depIdxs,
		EnumInfos:         file_nlp_dialog_special_event_proto_enumTypes,
		MessageInfos:      file_nlp_dialog_special_event_proto_msgTypes,
	}.Build()
	File_nlp_dialog_special_event_proto = out.File
	file_nlp_dialog_special_event_proto_rawDesc = nil
	file_nlp_dialog_special_event_proto_goTypes = nil
	file_nlp_dialog_special_event_proto_depIdxs = nil
}
