// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: classification/classification.proto

package classification

import (
	_ "github.com/ClarabridgeInc/ingestion-callback/internal/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// ClassificationResult
//
// model_results                      Classification results for a list of models.
// cda_results                        Classification results for CDA.
// intelligent_score_results          Results for intelligent score.
type DocumentClassificationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version                 int32                     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ModelResults            []*ModelResult            `protobuf:"bytes,2,rep,name=model_results,json=modelResults,proto3" json:"model_results,omitempty"`
	CdaResults              []*CDAResult              `protobuf:"bytes,3,rep,name=cda_results,json=cdaResults,proto3" json:"cda_results,omitempty"`
	IntelligentScoreResults []*IntelligentScoreResult `protobuf:"bytes,4,rep,name=intelligent_score_results,json=intelligentScoreResults,proto3" json:"intelligent_score_results,omitempty"`
}

func (x *DocumentClassificationResult) Reset() {
	*x = DocumentClassificationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentClassificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentClassificationResult) ProtoMessage() {}

func (x *DocumentClassificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentClassificationResult.ProtoReflect.Descriptor instead.
func (*DocumentClassificationResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentClassificationResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentClassificationResult) GetModelResults() []*ModelResult {
	if x != nil {
		return x.ModelResults
	}
	return nil
}

func (x *DocumentClassificationResult) GetCdaResults() []*CDAResult {
	if x != nil {
		return x.CdaResults
	}
	return nil
}

func (x *DocumentClassificationResult) GetIntelligentScoreResults() []*IntelligentScoreResult {
	if x != nil {
		return x.IntelligentScoreResults
	}
	return nil
}

//*
// SentenceClassificationResult
//
// model_results                      Classification results for a list of models.
type SentenceClassificationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      int32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ModelResults []*ModelResult `protobuf:"bytes,2,rep,name=model_results,json=modelResults,proto3" json:"model_results,omitempty"`
}

func (x *SentenceClassificationResult) Reset() {
	*x = SentenceClassificationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentenceClassificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceClassificationResult) ProtoMessage() {}

func (x *SentenceClassificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceClassificationResult.ProtoReflect.Descriptor instead.
func (*SentenceClassificationResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{1}
}

func (x *SentenceClassificationResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SentenceClassificationResult) GetModelResults() []*ModelResult {
	if x != nil {
		return x.ModelResults
	}
	return nil
}

//*
// ModelResult
//
// model_id                           ID of the model.
// index_suffix                       The current index suffix of the model
// classification_ts                  Timestamp when classification result is generated.
// node_results                       A list of nodes the document or sentence is classified to.
// model_name                         Name of the model.
// root_only                          Whether the document / sentence is only classified to the root node.
// root_node_id                       ID of the root node
type ModelResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ModelId          int64                  `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	IndexSuffix      *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=index_suffix,json=indexSuffix,proto3" json:"index_suffix,omitempty"`
	ClassificationTs int64                  `protobuf:"varint,4,opt,name=classification_ts,json=classificationTs,proto3" json:"classification_ts,omitempty"`
	NodeResults      []*NodeResult          `protobuf:"bytes,5,rep,name=node_results,json=nodeResults,proto3" json:"node_results,omitempty"`
	ModelName        string                 `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	RootOnly         bool                   `protobuf:"varint,7,opt,name=root_only,json=rootOnly,proto3" json:"root_only,omitempty"`
	RootNodeId       int64                  `protobuf:"varint,8,opt,name=root_node_id,json=rootNodeId,proto3" json:"root_node_id,omitempty"`
}

func (x *ModelResult) Reset() {
	*x = ModelResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResult) ProtoMessage() {}

func (x *ModelResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResult.ProtoReflect.Descriptor instead.
func (*ModelResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{2}
}

func (x *ModelResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ModelResult) GetModelId() int64 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *ModelResult) GetIndexSuffix() *wrapperspb.Int64Value {
	if x != nil {
		return x.IndexSuffix
	}
	return nil
}

func (x *ModelResult) GetClassificationTs() int64 {
	if x != nil {
		return x.ClassificationTs
	}
	return 0
}

func (x *ModelResult) GetNodeResults() []*NodeResult {
	if x != nil {
		return x.NodeResults
	}
	return nil
}

func (x *ModelResult) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelResult) GetRootOnly() bool {
	if x != nil {
		return x.RootOnly
	}
	return false
}

func (x *ModelResult) GetRootNodeId() int64 {
	if x != nil {
		return x.RootNodeId
	}
	return 0
}

//*
// Node Result
//
// node_id                            ID of the node.
// node_path                          Path of the node (a list of id from the root joined by /).
// node_name                          Name of the node.
type NodeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	NodeId   int64  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodePath string `protobuf:"bytes,3,opt,name=node_path,json=nodePath,proto3" json:"node_path,omitempty"`
	NodeName string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *NodeResult) Reset() {
	*x = NodeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResult) ProtoMessage() {}

func (x *NodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResult.ProtoReflect.Descriptor instead.
func (*NodeResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{3}
}

func (x *NodeResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeResult) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeResult) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *NodeResult) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

//*
// CDAResult
//
// attribute_id          ID of the attribute.
// attribute_name        Name of the attribute.
// values                The values of CDA (a list of topic names).
type CDAResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	AttributeId   int64    `protobuf:"varint,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	AttributeName string   `protobuf:"bytes,3,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	Values        []string `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *CDAResult) Reset() {
	*x = CDAResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CDAResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDAResult) ProtoMessage() {}

func (x *CDAResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDAResult.ProtoReflect.Descriptor instead.
func (*CDAResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{4}
}

func (x *CDAResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CDAResult) GetAttributeId() int64 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

func (x *CDAResult) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *CDAResult) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

//*
// IntelligentScoreResult
//
// score_card_id                ID of the score card.
// score                        Score value for this card.
type IntelligentScoreResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ScoreCardId int64                  `protobuf:"varint,2,opt,name=score_card_id,json=scoreCardId,proto3" json:"score_card_id,omitempty"`
	Score       *wrapperspb.FloatValue `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *IntelligentScoreResult) Reset() {
	*x = IntelligentScoreResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classification_classification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntelligentScoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelligentScoreResult) ProtoMessage() {}

func (x *IntelligentScoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_classification_classification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelligentScoreResult.ProtoReflect.Descriptor instead.
func (*IntelligentScoreResult) Descriptor() ([]byte, []int) {
	return file_classification_classification_proto_rawDescGZIP(), []int{5}
}

func (x *IntelligentScoreResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IntelligentScoreResult) GetScoreCardId() int64 {
	if x != nil {
		return x.ScoreCardId
	}
	return 0
}

func (x *IntelligentScoreResult) GetScore() *wrapperspb.FloatValue {
	if x != nil {
		return x.Score
	}
	return nil
}

var File_classification_classification_proto protoreflect.FileDescriptor

var file_classification_classification_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x1c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x40, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x64, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x44, 0x41, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x0a, 0x63, 0x64, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x62, 0x0a,
	0x19, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x22, 0x7f, 0x0a, 0x1c, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e,
	0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x40, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x22, 0xd1, 0x02, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x2b, 0x0a, 0x11,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x6e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x74,
	0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x22, 0x7e, 0x0a, 0x0a, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x22, 0x8c, 0x01, 0x0a, 0x09,
	0x43, 0x44, 0x41, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x22, 0x8e, 0x01, 0x0a, 0x16, 0x49,
	0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x3a, 0x03, 0xc0, 0x3e, 0x01, 0x42, 0x3b, 0x0a, 0x24, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x01, 0x5a, 0x11, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_classification_classification_proto_rawDescOnce sync.Once
	file_classification_classification_proto_rawDescData = file_classification_classification_proto_rawDesc
)

func file_classification_classification_proto_rawDescGZIP() []byte {
	file_classification_classification_proto_rawDescOnce.Do(func() {
		file_classification_classification_proto_rawDescData = protoimpl.X.CompressGZIP(file_classification_classification_proto_rawDescData)
	})
	return file_classification_classification_proto_rawDescData
}

var file_classification_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_classification_classification_proto_goTypes = []interface{}{
	(*DocumentClassificationResult)(nil), // 0: classification.DocumentClassificationResult
	(*SentenceClassificationResult)(nil), // 1: classification.SentenceClassificationResult
	(*ModelResult)(nil),                  // 2: classification.ModelResult
	(*NodeResult)(nil),                   // 3: classification.NodeResult
	(*CDAResult)(nil),                    // 4: classification.CDAResult
	(*IntelligentScoreResult)(nil),       // 5: classification.IntelligentScoreResult
	(*wrapperspb.Int64Value)(nil),        // 6: google.protobuf.Int64Value
	(*wrapperspb.FloatValue)(nil),        // 7: google.protobuf.FloatValue
}
var file_classification_classification_proto_depIdxs = []int32{
	2, // 0: classification.DocumentClassificationResult.model_results:type_name -> classification.ModelResult
	4, // 1: classification.DocumentClassificationResult.cda_results:type_name -> classification.CDAResult
	5, // 2: classification.DocumentClassificationResult.intelligent_score_results:type_name -> classification.IntelligentScoreResult
	2, // 3: classification.SentenceClassificationResult.model_results:type_name -> classification.ModelResult
	6, // 4: classification.ModelResult.index_suffix:type_name -> google.protobuf.Int64Value
	3, // 5: classification.ModelResult.node_results:type_name -> classification.NodeResult
	7, // 6: classification.IntelligentScoreResult.score:type_name -> google.protobuf.FloatValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_classification_classification_proto_init() }
func file_classification_classification_proto_init() {
	if File_classification_classification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_classification_classification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentClassificationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classification_classification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentenceClassificationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classification_classification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classification_classification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classification_classification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CDAResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classification_classification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntelligentScoreResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_classification_classification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_classification_classification_proto_goTypes,
		DependencyIndexes: file_classification_classification_proto_depIdxs,
		MessageInfos:      file_classification_classification_proto_msgTypes,
	}.Build()
	File_classification_classification_proto = out.File
	file_classification_classification_proto_rawDesc = nil
	file_classification_classification_proto_goTypes = nil
	file_classification_classification_proto_depIdxs = nil
}
