// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: storage/relation-storage.proto

package storage

import (
	nlpbase "github.com/ClarabridgeInc/ingestion-callback/internal/pb/nlpbase"
	_ "github.com/ClarabridgeInc/ingestion-callback/internal/pb/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Relation
//
// version              Message version.
// src_token_start_pos  Token start position relative to sentence.
// dst_token_start_pos  Token end position relative to sentence.
// type                 Relation type.
type Relation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          int32                `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	SrcTokenStartPos int32                `protobuf:"varint,1,opt,name=src_token_start_pos,json=srcTokenStartPos,proto3" json:"src_token_start_pos,omitempty"`
	DstTokenStartPos int32                `protobuf:"varint,2,opt,name=dst_token_start_pos,json=dstTokenStartPos,proto3" json:"dst_token_start_pos,omitempty"`
	Type             nlpbase.RelationType `protobuf:"varint,3,opt,name=type,proto3,enum=nlp.RelationType" json:"type,omitempty"`
}

func (x *Relation) Reset() {
	*x = Relation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_relation_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_storage_relation_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_storage_relation_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Relation) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Relation) GetSrcTokenStartPos() int32 {
	if x != nil {
		return x.SrcTokenStartPos
	}
	return 0
}

func (x *Relation) GetDstTokenStartPos() int32 {
	if x != nil {
		return x.DstTokenStartPos
	}
	return 0
}

func (x *Relation) GetType() nlpbase.RelationType {
	if x != nil {
		return x.Type
	}
	return nlpbase.RelationType(0)
}

var File_storage_relation_storage_proto protoreflect.FileDescriptor

var file_storage_relation_storage_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x6e, 0x6c, 0x70, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xae, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x13, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x72, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x13, 0x64, 0x73, 0x74, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x64, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x6f, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x3a, 0x03, 0xc0, 0x3e, 0x06,
	0x42, 0x2d, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x61, 0x72, 0x61, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x50, 0x01, 0x5a, 0x0a, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_relation_storage_proto_rawDescOnce sync.Once
	file_storage_relation_storage_proto_rawDescData = file_storage_relation_storage_proto_rawDesc
)

func file_storage_relation_storage_proto_rawDescGZIP() []byte {
	file_storage_relation_storage_proto_rawDescOnce.Do(func() {
		file_storage_relation_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_relation_storage_proto_rawDescData)
	})
	return file_storage_relation_storage_proto_rawDescData
}

var file_storage_relation_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storage_relation_storage_proto_goTypes = []interface{}{
	(*Relation)(nil),          // 0: storage.Relation
	(nlpbase.RelationType)(0), // 1: nlp.RelationType
}
var file_storage_relation_storage_proto_depIdxs = []int32{
	1, // 0: storage.Relation.type:type_name -> nlp.RelationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storage_relation_storage_proto_init() }
func file_storage_relation_storage_proto_init() {
	if File_storage_relation_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_relation_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_relation_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_relation_storage_proto_goTypes,
		DependencyIndexes: file_storage_relation_storage_proto_depIdxs,
		MessageInfos:      file_storage_relation_storage_proto_msgTypes,
	}.Build()
	File_storage_relation_storage_proto = out.File
	file_storage_relation_storage_proto_rawDesc = nil
	file_storage_relation_storage_proto_goTypes = nil
	file_storage_relation_storage_proto_depIdxs = nil
}
