// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: dataservice/ds-write-sqsconsumer.proto

package dataservice

import (
	ingest "github.com/ClarabridgeInc/ingestion-callback/internal/pb/services/ingest"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DsWriteMessageOperationType int32

const (
	DsWriteMessageOperationType_CREATE DsWriteMessageOperationType = 0
	DsWriteMessageOperationType_UPDATE DsWriteMessageOperationType = 1
	DsWriteMessageOperationType_DELETE DsWriteMessageOperationType = 2
	DsWriteMessageOperationType_BULK   DsWriteMessageOperationType = 3
)

// Enum value maps for DsWriteMessageOperationType.
var (
	DsWriteMessageOperationType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "BULK",
	}
	DsWriteMessageOperationType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
		"BULK":   3,
	}
)

func (x DsWriteMessageOperationType) Enum() *DsWriteMessageOperationType {
	p := new(DsWriteMessageOperationType)
	*p = x
	return p
}

func (x DsWriteMessageOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DsWriteMessageOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_dataservice_ds_write_message_proto_enumTypes[0].Descriptor()
}

func (DsWriteMessageOperationType) Type() protoreflect.EnumType {
	return &file_dataservice_ds_write_message_proto_enumTypes[0]
}

func (x DsWriteMessageOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DsWriteMessageOperationType.Descriptor instead.
func (DsWriteMessageOperationType) EnumDescriptor() ([]byte, []int) {
	return file_dataservice_ds_write_message_proto_rawDescGZIP(), []int{0}
}

//*
// DsWriteMessage
// Message for writing data to elastic search via Data Service
//
// metadata  sqsconsumer metadata
// body      data that are supposed to be store to elastic search
type DsWriteMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *DsWriteMessageMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are assignable to Body:
	//	*DsWriteMessage_JsonRequest
	//	*DsWriteMessage_IngestDocument
	Body isDsWriteMessage_Body `protobuf_oneof:"body"`
}

func (x *DsWriteMessage) Reset() {
	*x = DsWriteMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataservice_ds_write_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DsWriteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DsWriteMessage) ProtoMessage() {}

func (x *DsWriteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dataservice_ds_write_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DsWriteMessage.ProtoReflect.Descriptor instead.
func (*DsWriteMessage) Descriptor() ([]byte, []int) {
	return file_dataservice_ds_write_message_proto_rawDescGZIP(), []int{0}
}

func (x *DsWriteMessage) GetMetadata() *DsWriteMessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (m *DsWriteMessage) GetBody() isDsWriteMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *DsWriteMessage) GetJsonRequest() *DsJsonMessage {
	if x, ok := x.GetBody().(*DsWriteMessage_JsonRequest); ok {
		return x.JsonRequest
	}
	return nil
}

func (x *DsWriteMessage) GetIngestDocument() *ingest.IngestDocument {
	if x, ok := x.GetBody().(*DsWriteMessage_IngestDocument); ok {
		return x.IngestDocument
	}
	return nil
}

type isDsWriteMessage_Body interface {
	isDsWriteMessage_Body()
}

type DsWriteMessage_JsonRequest struct {
	JsonRequest *DsJsonMessage `protobuf:"bytes,2,opt,name=jsonRequest,proto3,oneof"`
}

type DsWriteMessage_IngestDocument struct {
	IngestDocument *ingest.IngestDocument `protobuf:"bytes,3,opt,name=ingestDocument,proto3,oneof"`
}

func (*DsWriteMessage_JsonRequest) isDsWriteMessage_Body() {}

func (*DsWriteMessage_IngestDocument) isDsWriteMessage_Body() {}

//*
// DsWriteMessageMetadata
// Metadata for DsWriteMessage.
//
// messageId        Unique identifier of a sqsconsumer. UUID.
// messageDateTime  Time in seconds when sqsconsumer was created
// operationType    Operation Type (enum).
type DsWriteMessageMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId       string                      `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	MessageDateTime *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=messageDateTime,proto3" json:"messageDateTime,omitempty"`
	OperationType   DsWriteMessageOperationType `protobuf:"varint,3,opt,name=operationType,proto3,enum=dataservice.DsWriteMessageOperationType" json:"operationType,omitempty"`
}

func (x *DsWriteMessageMetadata) Reset() {
	*x = DsWriteMessageMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataservice_ds_write_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DsWriteMessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DsWriteMessageMetadata) ProtoMessage() {}

func (x *DsWriteMessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dataservice_ds_write_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DsWriteMessageMetadata.ProtoReflect.Descriptor instead.
func (*DsWriteMessageMetadata) Descriptor() ([]byte, []int) {
	return file_dataservice_ds_write_message_proto_rawDescGZIP(), []int{1}
}

func (x *DsWriteMessageMetadata) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DsWriteMessageMetadata) GetMessageDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MessageDateTime
	}
	return nil
}

func (x *DsWriteMessageMetadata) GetOperationType() DsWriteMessageOperationType {
	if x != nil {
		return x.OperationType
	}
	return DsWriteMessageOperationType_CREATE
}

type DsJsonMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=sqsconsumer,proto3" json:"sqsconsumer,omitempty"`
}

func (x *DsJsonMessage) Reset() {
	*x = DsJsonMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataservice_ds_write_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DsJsonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DsJsonMessage) ProtoMessage() {}

func (x *DsJsonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dataservice_ds_write_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DsJsonMessage.ProtoReflect.Descriptor instead.
func (*DsJsonMessage) Descriptor() ([]byte, []int) {
	return file_dataservice_ds_write_message_proto_rawDescGZIP(), []int{2}
}

func (x *DsJsonMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dataservice_ds_write_message_proto protoreflect.FileDescriptor

var file_dataservice_ds_write_message_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x73,
	0x2d, 0x77, 0x72, 0x69, 0x74, 0x65, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x2d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xdb, 0x01, 0x0a, 0x0e, 0x44, 0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69,
	0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xcc,
	0x01, 0x0a, 0x16, 0x44, 0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x4e, 0x0a,
	0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x44, 0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a,
	0x0d, 0x44, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x4b, 0x0a, 0x1b, 0x44, 0x73, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54,
	0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42,
	0x55, 0x4c, 0x4b, 0x10, 0x03, 0x42, 0x35, 0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6c, 0x61,
	0x72, 0x61, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x0e, 0x70, 0x62,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataservice_ds_write_message_proto_rawDescOnce sync.Once
	file_dataservice_ds_write_message_proto_rawDescData = file_dataservice_ds_write_message_proto_rawDesc
)

func file_dataservice_ds_write_message_proto_rawDescGZIP() []byte {
	file_dataservice_ds_write_message_proto_rawDescOnce.Do(func() {
		file_dataservice_ds_write_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataservice_ds_write_message_proto_rawDescData)
	})
	return file_dataservice_ds_write_message_proto_rawDescData
}

var file_dataservice_ds_write_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dataservice_ds_write_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dataservice_ds_write_message_proto_goTypes = []interface{}{
	(DsWriteMessageOperationType)(0), // 0: dataservice.DsWriteMessageOperationType
	(*DsWriteMessage)(nil),           // 1: dataservice.DsWriteMessage
	(*DsWriteMessageMetadata)(nil),   // 2: dataservice.DsWriteMessageMetadata
	(*DsJsonMessage)(nil),            // 3: dataservice.DsJsonMessage
	(*ingest.IngestDocument)(nil),    // 4: ingest.IngestDocument
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_dataservice_ds_write_message_proto_depIdxs = []int32{
	2, // 0: dataservice.DsWriteMessage.metadata:type_name -> dataservice.DsWriteMessageMetadata
	3, // 1: dataservice.DsWriteMessage.jsonRequest:type_name -> dataservice.DsJsonMessage
	4, // 2: dataservice.DsWriteMessage.ingestDocument:type_name -> ingest.IngestDocument
	5, // 3: dataservice.DsWriteMessageMetadata.messageDateTime:type_name -> google.protobuf.Timestamp
	0, // 4: dataservice.DsWriteMessageMetadata.operationType:type_name -> dataservice.DsWriteMessageOperationType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dataservice_ds_write_message_proto_init() }
func file_dataservice_ds_write_message_proto_init() {
	if File_dataservice_ds_write_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataservice_ds_write_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DsWriteMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataservice_ds_write_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DsWriteMessageMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataservice_ds_write_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DsJsonMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dataservice_ds_write_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DsWriteMessage_JsonRequest)(nil),
		(*DsWriteMessage_IngestDocument)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataservice_ds_write_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dataservice_ds_write_message_proto_goTypes,
		DependencyIndexes: file_dataservice_ds_write_message_proto_depIdxs,
		EnumInfos:         file_dataservice_ds_write_message_proto_enumTypes,
		MessageInfos:      file_dataservice_ds_write_message_proto_msgTypes,
	}.Build()
	File_dataservice_ds_write_message_proto = out.File
	file_dataservice_ds_write_message_proto_rawDesc = nil
	file_dataservice_ds_write_message_proto_goTypes = nil
	file_dataservice_ds_write_message_proto_depIdxs = nil
}
